apiVersion: v1
kind: Namespace
metadata:
  name: awx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-operator
  namespace: awx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: awx-operator
  template:
    metadata:
      labels:
        name: awx-operator
    spec:
      containers:
      - name: awx-operator
        image: quay.io/ansible/awx-operator:latest
        env:
        - name: WATCH_NAMESPACE
          value: awx