apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: LoadBalancer
  postgres_configuration_secret: awx-postgres-configuration
  admin_user: admin
  admin_password_secret: awx-admin-password
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: postgres
  port: "5432"
  database: awx
  username: awx
  password: awxpass
  type: managed
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: awx
stringData:
  password: password